[theme]
base = "light"
primaryColor = "#6366F1"
font = "sans serif"
baseRadius = "large"
buttonRadius = "large"
showWidgetBorder = true
showSidebarBorder = true

[theme.sidebar]
showWidgetBorder = true
